import React from "react";
import Resource from "./page";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Resource of  HomeDecor - For more beutiful Hause ",
  description: "Generated by create next app",
};

function Layout() {
  return (
    <section>
      <div>
        <Resource />
      </div>
    </section>
  );
}

export default Layout;
